@extends('layouts.app') 

@section('content')
    <h1>{{$title}}</h1>
    <br>
    <h4>Sejarah SMKN 3 Mataram</h4>
    <br>
    <p>Sekolah ini semula didirikan pada tahun 1962 atas prakarsa guru-guru STN I dan STN II (Sekolah Tehnik Negeri) , bersama-sama tenaga dari Dinas PU (Pekerjaan Umum) Propinsi Nusa Tenggara Barat.</p>
    <p>Pimpinan pertama STM ini adalah Bapak EFENDI BRE dan diberi nama STM Lembaga. Kemudian sesuai dengan semangat pada saat itu, STM Lembaga ini mulai tahun 1963 sempai 1964, bernama STM Takari (Tahun Kemenangan Republik Indonesia) dengan Kepala Sekolah Bapak MASNUN.</p>
    <p>Perjuangan demi perjuangan sesuai dengan tuntutan zaman dan semakin banyaknya tamatam STN I dan STN II timbul perkembangan baru dengan inisiatif Persatuan Orang Tua Murid dan Guru-Guru (POMG), STM TAKARI ini tidak lama dipegang oleh Bapak Ir. MASNUN, kemudian diserahterimakan kepada Bapak Ir. RAMBE sampai tahun 1969 yang pada saat itu juga menjabat Kepala Kantor Pekerjaan Umum (PU) Provinsi NTB. Karena kesehatan yang tidak mengijinkan untuk memimpin STM TAKARI, maka Jabatan Kepala Sekolah diserahkan kepada Bapak I WAYAN KERTHIN dari STM NEGERI DENPASAR, yang kemudian status STM TAKARI berubah menjadi STM MATARAM FILIAL DENPASAR. Jurusan yang ada pada saat itu adalah MESIN UMUM DAN BANGUNAN. Tetapi karena STM Negeri Denpasar sendiri kekurangan guru, maka pada awal tahun ajaran 1970, pimpinan STM Mataram Filial Denpasar diserahkan kepada Bapak I MADE KOEPI, yang waktu itu menjabat Kepala Inspeksi Daerah Pendidikan Teknik (IDPT) Perwakilan Pendidikan dan Kebudayaan Propinsi NTB, yang juga menjabat kepala sekolah STN I dan STN II, serta STM Mataram Filial Denpasar. Kedudukan pusat STM Mataram Filial Denpasar bertempat di STN I dan STN II Mataram Jl. Pejanggik.</p>
    <p>Untuk praktek Jurusan Bangunan Gedung di Jl. Lemuru Baru (sekarang Jln. Pendidikan), sedangkan untuk Jurusan Mesin Umum tetap di Jln. Pejanggik.</p>
    <p>Setelah menamatkan dua kali masa belajar, STM Mataram Filial Denpasar yang pertama 10 orang, dan yang keduia 20 orang, maka dengan Surat Keputusan Menteri Departemen Pendidikan dan Kebudayaan Nomor: 0243/1970 tanggal 28 Desember 1970 STM Mataram status Filial berubah menjadi STM NEGERI MATARAM penuh yang berkedudukan di Jl. Pejanggik dan Kepala Sekolah masih dipegang oleh Bapak I MADE KOEPI.</p>
    <p>Penyelenggaraan ujian dilaksanakan sepenuhnya di Mataram, baik praktek, teori maupun meluluskan ujian pertama kali sampai dengan meluluskan siswa mulai tahun 1971 di Mataram. Karena Bapak I Made Koepi pensiun tahun 1971, Kepala Sekolah STM Negeri Mataram mulai tahun 1972 diserahkan kepada Bapak JANUAR ARDANA PUTRA, BSc.</p>
    <p>Semua kegiatan dipindahkan dari Jln. Pejanggik ke Jln. Pendidikan, dengan Jurusan yang tetap yaitu MESIN UMUM dan BANGUNAN GEDUNG. Mulai tahu 1975, STM Negeri Mataram mendapat giliran memperoleh biaya pengembangan pendidikan dari program pembangunan lima tahun (Pelita), maka semua perlengkapan, alat dan bahan untuk praktek siswa sedikit demi sedikit dilengkapi.</p>
    <p>Pada bulan Desember 1975, Bapak JANUAR ARDANA PUTRA menerima tugas baru dari Jakarta untuk memimpin sekolah-sekolah Indonesia yang ada di India, maka tugas kepala Sekolah dialihkan kepada Bapak MUKHTARUDDIN HADI, BSc. Sedangkan Jurusan yang ada yang semula Mesin Umum berubah menjadi MESIN PRODUKSI sedangkan untuk Jurusan Bangunan tetap, ditambah satu jurusan yaitu Jurusan LISTRIK. Sejak tahun ajaran 1976 sampai 1977, selama perkembangan STM NEGERI MATARAM sempat mencatat kegiatan olah raga yang menonjol terutama bidang sepak bola, volleyball dan kesenian. Sehingga menjadi pusat perhatian sekolah-sekolah menengah ke atas sekota Mataram.</p>
    <p>Tahun 1982, karena tugas kemudian bapak MUKHTARUDDIN HADI, BSc, dipindahkan ke staf di DIKMENJUR KANWIL DEPDIKBUD Provinsi NTB. Tugas Kepala Sekolah sementara dipegang Bapak R.SUBADO HS. Selama dipegang Bapak R.SUBADO HS, kemudian di tambah satu Jurusan lagi yaitu JURUSAN OTOMOTIF TAHUN 1982, dan pada tahun 1985 dibukalah Jurusan Elektronika Komunikasi, sehingga lengkaplah Jurusan menjadi 5 (lima) Jurusan atau dinamakan 5 (lima) Rumpun.</p>
@endsection
